### ISSUE TITLE
merci de le vendre ou merci de le vendu ?

### ISSUE THREAD

**Issue by bpaulin** [BriceMichalski/on-mange-quoi#12]
https://github.com/BriceMichalski/on-mange-quoi/blob/1050123bd92b7aeecf30d104e5ba64d21c3ff945/public/index.html#L14

**Comment by BriceMichalski** [comment]
fix in  [829d99016edac65d9892d257b49edcb6afb52a89](https://github.com/BriceMichalski/on-mange-quoi/commit/829d99016edac65d9892d257b49edcb6afb52a89)
